#ifndef _CONSTANTS_MMU_HPP_
#define _CONSTANTS_MMU_HPP_

#define STATIC_ROM_START 0x0000
#define STATIC_ROM_END 0x3fff
#define STATIC_ROM_SIZE 0x4000

#define SWITCHABLE_ROM_START 0x4000
#define SWITCHABLE_ROM_END 0x7fff
#define SWITCHABLE_ROM_SIZE 0x4000

#define VRAM_START 0x8000
#define VRAM_END 0x9fff
#define VRAM_SIZE 0x2000

#define SWITCHABLE_RAM_START 0xa000
#define SWITCHABLE_RAM_END 0xbfff
#define SWITCHABLE_RAM_SIZE 0x2000

#define INTERNAL_RAM_START 0xc000
#define INTERNAL_RAM_END 0xdfff
#define INTERNAL_RAM_SIZE 0x2000

#define SPRITE_ATTRIBUTES_START 0xfe00
#define SPRITE_ATTRIBUTES_END 0xfe9f
#define SPRITE_ATTRIBUTES_SIZE 0xa0

#define I_O_START 0xff00
#define I_O_END 0xff4b
#define I_O_SIZE 0x4c

#define HIGH_RAM_START 0xff80
#define HIGH_RAM_END 0xfffe
#define HIGH_RAM_SIZE 0x7f

#define INTERRUPT_REGISTER_ADDR 0xffff

#define RAM_ENABLE_START 0x0000
#define RAM_ENABLE_END 0x1fff
#define ROM_BANK_SELECT_START 0x2000
#define ROM_BANK_SELECT_END 0x3fff
#define RAM_BANK_SELECT_START 0x4000
#define RAM_BANK_SELECT_END 0x5fff
#define BANKING_MODE_START 0x6000
#define BANKING_MODE_END 0x7fff

#define HEADER_ROM_SIZE_ADDR 0x0148
#define HEADER_RAM_SIZE_ADDR 0x0149

#define DEFAULT_READ_RETURN 0xff

#define MBC1_ROM_BANKS_MASK 0x1f
#define MBC1_RAM_BANKS_MASK 0x03
#define MBC1_RAM_ENABLE_MASK 0x0f
#define MBC1_RAM_ENABLE_ENABLED 0x0a

#endif