#ifndef _CONSTANTS_HPP_
#define _CONSTANTS_HPP_

#define STATIC_ROM_START 0x0000
#define STATIC_ROM_END 0x3fff
#define STATIC_ROM_SIZE 0x4000

#define SWITCHABLE_ROM_START 0x4000
#define SWITCHABLE_ROM_END 0x7fff
#define SWITCHABLE_ROM_SIZE 0x4000

#define BANK_SWITCHING_START 0x2000
#define BANK_SWITCHING_END 0x3fff

#define ROM_BANKS_MASK 0x1f

#endif